cat lms_deploy.yml
---
- hosts: "{{ host | default('live,bulk,login,usermgmt,task,cron,lmsdr') }}"
  vars:
    env : "{{ ENV|default('AZUREUAT') }}"
    node_version : "{{ NODE_VERSION | default('4.8.4')}}"
    nvm_version : "v0.33.2"
    repoupdate : "true"
    install : "{{ INSTALL | default('false') }}"
    branch : "{{ BRANCH | default('production') }}"
    user : "{{ USER | default('ubuntu') }}"
    repository : "lms"
    service : "lms"
    startScriptName : "start_lms_server"
    directory : "/var/log/vymo"
    defaultStartupLog : "{{ DEFAULT_STARTUP_LOG | default('syslog') }} "
    cloudName : "AZURE"
    log_level : "INFO"
    service_port: "{{ PORT | default('3002') }}"
    health_url: "health"
    npminstall: "{{ NPMINSTALL | default('true') }}"
    npmreset: "{{ NPMRESET | default('false') }}"
    tag: "{{ TAG | default('') }}"
    healthkeyword: "success"
    sleeptime: "{{ SLEEPTIME }}"
    checkKey: "{{ service }}"

  gather_facts: no
  max_fail_percentage: 20
  serial:
  - "10%"
  - "20%"
  - "40%"
  - "70%"
  - "100%"
  roles:
    - build-essentials
    - installNode
    - forever
    - createFolder
    - git
    - genericNodejsService
    - { role: bringoutLB, when: ('config-service-server' not in group_names) and ('sso' not in group_names) }
    - restartService
    - { role: healthCheck, when: ('config-service-server' not in group_names) and ('sso' not in group_names) }

